Modify find command to allow find substrings in words
CS2103AUG2016-T14-C4/main pull request #31
Opened 2016-10-12 09:08 UTC by Skaty

2016-10-12 15:59 UTC, advaypal commented on src/main/java/seedu/address/commons/util/StringUtil.java
> +        List<String> strings = listifyString(source);
These changes are in the other PR too. Please don't duplicate code like this across PRs

2016-10-12 15:59 UTC, advaypal commented on src/main/java/seedu/address/model/ModelManager.java
> +    private class NameSubstringQualifier implements Qualifier {
Same thing here

2016-10-12 16:00 UTC, advaypal requested changes
All the changes of this PR(except the tests I think) are in the other PR too. Please don't do something like this again. For now you can add the test in that PR, along with the other comments I made there, and can then close this PR.

2016-10-13 06:43 UTC, Skaty commented
Refer to #30

2016-10-13 06:43 UTC, closed without merging