Add date time to model
CS2103AUG2016-T14-C4/main pull request #45
Opened 2016-10-18 12:36 UTC by advaypal

An incomplete PR. The add command works for all tasks, but is not complete, and test cases are not extensive. This PR has been made due to the urgent need for a working DateTime model.

2016-10-18 12:43 UTC, Skaty requested changes

2016-10-18 12:43 UTC, Skaty commented on src/main/java/seedu/task/storage/XmlAdaptedTask.java
> +        final DateTime openTime = new DateTime(null); //TODO: WRITE PROPER TEST
Why null?

2016-10-18 12:43 UTC, Skaty commented on src/main/java/seedu/task/logic/parser/Parser.java
> +                    + "( s/(?<openTime>[^/]+))?"
Remove the spaces

2016-10-18 13:30 UTC, advaypal commented on src/main/java/seedu/task/storage/XmlAdaptedTask.java
> +        final DateTime openTime = new DateTime(null); //TODO: WRITE PROPER TEST
Will be changed. Just for now

2016-10-18 13:31 UTC, advaypal commented on src/main/java/seedu/task/logic/parser/Parser.java
> +                    + "( s/(?<openTime>[^/]+))?"
I thought the space is needed? Will check

2016-10-19 14:12 UTC, Skaty requested changes
I'll resolve the merge conflict once you are done with the changes.

2016-10-19 14:12 UTC, Skaty commented on src/main/java/seedu/task/logic/commands/UpdateCommand.java
> +            e1.printStackTrace();
Don't print stackTrace

2016-10-19 14:12 UTC, Skaty commented on src/main/java/seedu/task/model/task/Task.java
> +        // TODO Auto-generated method stub
Remove this auto generated comment.

2016-10-19 14:12 UTC, Skaty commented on src/main/java/seedu/task/model/task/Task.java
> +        // TODO Auto-generated method stub
Remove this auto generated comment.

2016-10-19 14:12 UTC, Skaty commented on src/test/java/guitests/TaskManagerGuiTest.java
> +            // TODO Auto-generated catch block
Remove this auto generated comment.

2016-10-19 14:12 UTC, Skaty commented on src/test/java/seedu/task/testutil/TypicalTestTasks.java
> +            // TODO Auto-generated catch block
Remove this auto generated comment.

2016-10-19 14:12 UTC, Skaty commented on src/test/java/guitests/guihandles/TaskListPanelHandle.java
> +            // TODO Auto-generated catch block
Remove this auto generated comment.

2016-10-19 14:12 UTC, Skaty commented on src/test/java/seedu/task/testutil/TypicalTestTasks.java
> +            e.printStackTrace();
Can change to `assert false: "reason"` instead? Because this exception will not happen unless someone happens to make the wrong sample tasks.

2016-10-19 14:35 UTC, advaypal commented on src/main/java/seedu/task/logic/commands/UpdateCommand.java
> +            e1.printStackTrace();
Alternative?

2016-10-19 14:51 UTC, Skaty commented on src/main/java/seedu/task/logic/commands/UpdateCommand.java
> +            e1.printStackTrace();
Log it using the logger.

2016-10-19 15:13 UTC, advaypal commented on src/main/java/seedu/task/logic/commands/UpdateCommand.java
> +            e1.printStackTrace();
Dammit I already pushed. Just merge for now, will add it later

2016-10-19 15:27 UTC, advaypal commented
@Skaty changes done

2016-10-19 17:21 UTC, Skaty approved these changes
:+!:

2016-10-19 17:21 UTC, merged