Add aliasing
CS2103AUG2016-T14-C4/main pull request #82
Opened 2016-11-02 14:15 UTC by advaypal

Add aliasing of commands.

2016-11-02 16:39 UTC, Skaty commented
Fix codacity and coveralls.

2016-11-02 16:48 UTC, advaypal commented
Coveralls is down because I uncommented a storage test. Same reason as in the other PR. Merge it in for now, I need to figure out why that test causes a bug

2016-11-02 16:49 UTC, advaypal commented
Am fixing codacy

2016-11-02 16:52 UTC, Skaty requested changes
Overall okay. Please check your syntax and follow Java coding standard given.

2016-11-02 16:52 UTC, Skaty commented on src/test/java/guitests/ChangePathCommandTest.java
> +        //TEMPORARY> NEED TO FIX TEST
Don't leave unused code in comments. Please remove. (That's one of the things Git can handle)

2016-11-02 16:52 UTC, Skaty commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +        String generateAddCommand(String alias, Task p) {
Why the change?

2016-11-02 16:52 UTC, Skaty commented on src/main/java/seedu/task/logic/commands/AliasCommand.java
> +        if(alias != null && command != null) {
`if (alias != null && command != null) {`. Proper spacing.

2016-11-02 16:52 UTC, Skaty commented on src/main/java/seedu/task/logic/parser/AliasParser.java
> +        if(getSingleKeywordArgValue(FLAG_ALIAS_COMMAND) != null && getSingleKeywordArgValue(FLAG_ALIAS_VALUE) != null) {
`getSingleKeywordArgValue(FLAG_ALIAS_COMMAND)` can be set as a variable, since you use it again?

2016-11-02 16:52 UTC, Skaty commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +    public void execute_alias_successful() throws Exception {
Test cases for alias unsuccessful?

2016-11-02 17:15 UTC, advaypal commented on src/test/java/guitests/ChangePathCommandTest.java
> +        //TEMPORARY> NEED TO FIX TEST
That's temporary. That test screws up the config file, but I need to have a test there. WIll resolve in later PR, it's not related to alias

2016-11-02 17:15 UTC, advaypal commented on src/main/java/seedu/task/logic/commands/AliasCommand.java
> +        if(alias != null && command != null) {
Ok

2016-11-02 17:17 UTC, advaypal commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +    public void execute_alias_successful() throws Exception {
It's there, see the tests just above this one

2016-11-02 17:18 UTC, advaypal commented on src/test/java/seedu/task/logic/LogicManagerTest.java
> +        String generateAddCommand(String alias, Task p) {
Because it's testing aliases as well as add

2016-11-02 17:20 UTC, advaypal commented on src/main/java/seedu/task/logic/parser/AliasParser.java
> +        if(getSingleKeywordArgValue(FLAG_ALIAS_COMMAND) != null && getSingleKeywordArgValue(FLAG_ALIAS_VALUE) != null) {
can

2016-11-03 01:20 UTC, Skaty approved these changes

2016-11-03 01:20 UTC, merged