Update user guide
CS2103AUG2016-T14-C4/main pull request #90
Opened 2016-11-04 00:43 UTC by SukiTsang

2016-11-06 14:06 UTC, advaypal commented
Travis is failing

2016-11-06 14:46 UTC, SukiTsang commented
Need to re-run the travis

2016-11-07 03:10 UTC, Skaty requested changes
Please see comments and reply/make changes.

2016-11-07 03:10 UTC, Skaty commented on docs/UserGuide.md
> +  Returns tasks having name `cs2103`
Name or substring.

2016-11-07 03:10 UTC, Skaty commented on docs/UserGuide.md
>  > * The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
Add the fact that you can search substrings e.g. `mee` will match `meeting`.

2016-11-07 03:10 UTC, Skaty commented on docs/UserGuide.md
> +Nowadays, everyone got so many tasks to do. Have you ever miss your deadlines or forget your schedule? MESS are here to help you! MESS is a to-do list application which reminds you of your tasks or e
Need to fix the grammar a little.

2016-11-07 03:17 UTC, SukiTsang commented on docs/UserGuide.md
> +Nowadays, everyone got so many tasks to do. Have you ever miss your deadlines or forget your schedule? MESS are here to help you! MESS is a to-do list application which reminds you of your tasks or e
Please check again, thanks. My grammar is not so good.

2016-11-07 04:56 UTC, Skaty approved these changes
:+1:, needs final fixing later on.

2016-11-07 04:56 UTC, merged